# Base interaction that involves hands
- type: Interaction
  id: BaseLips
  abstract: true
  requiresCanInteract: true
  contactInteraction: true
  range:
    max: 1.2
  effectSuccess:
    popup: Obvious
    sound: {path: /Audio/Floof/Lewd/kiss.ogg}
  effectFailure:
    popup: Fail
    sound: {path: /Audio/Floof/Lewd/kiss.ogg}
    
# Base interaction that involves hands
- type: Interaction
  id: BaseTongue
  abstract: true
  requiresCanInteract: true
  contactInteraction: true
  range:
    max: 1.2
  effectSuccess:
    popup: Obvious
    sound: {path: /Audio/Floof/Lewd/lick.ogg}
  effectFailure:
    popup: Fail
    sound: {path: /Audio/Floof/Lewd/lick.ogg}
